#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>
#include <sys/stat.h>
#include <dirent.h>
#include <errno.h>
#include <math.h>
#include <sys/sem.h>
#include <sys/wait.h>
#include <sys/shm.h>
#include <unistd.h>